### ISSUE TITLE
Template default.html.twig is not defined

### ISSUE THREAD

**Issue by diomed** [Carve/grav-theme-uikit#2]
Can this theme be updated and this error fixed:

RuntimeException (400)
Template "default.html.twig" is not defined.

**Comment by Carve** [comment]
Will be resolved this week.  Look for a new commit Wednesday or Thursday.

**Comment by diomed** [comment]
great. u could also update to newest version, along the way; it's 
https://github.com/uikit/uikit/releases/tag/v2.27.4-src

**Comment by Carve** [comment]
Done and done

**Comment by diomed** [comment]
hello. ummm... u maybe fixed it locally, but no changes are available on github?!!? 😕

**Comment by Carve** [comment]
https://github.com/Carve/grav-theme-uikit/commit/77950564beebf276114057dcd07157a4ada23fce

**Comment by diomed** [comment]
can u please make a new release https://help.github.com/articles/creating-releases/
so it would display as updated in grav downloads.

**Comment by Carve** [comment]
Done.
